seed: 42

cv_splits: 4
cv_models_dir: data/06_models/cv_folds

validation_size: 0.15

data_loader_workers: 6

classifier:
  gpus: -1
  batch_size: 10
  max_epochs: 100
  max_steps: 0
  auto_lr_find: 0
  lr: 0.001
  weight_decay: 0.0001
  early_stop_patience: 4
  reduce_lr_on_pleteau_patience: 3
  save_top_k_checkpoints: 1
  checkpoints_dir: data/06_models/classifier/checkpoints


byol:
  gpus: -1
  batch_size: 10
  max_epochs: 100
  max_steps: 0
  auto_lr_find: 1
  lr: 0.01
  reduce_lr_on_pleteau_patience: 1
  weight_decay: 0.0001
  limit_train_batches: 300
  limit_val_batches: 1
  accumulate_grad_batches: 4
  early_stop_patience: 3
  from_checkpoint: 0

  #limit_train_batches: 2

