seed: 42
cv_splits: 4
cv_models_dir: data/06_models/cv_folds
validation_size: 0.15
data_loader_workers: 4

classifier:
  train_height: 320
  train_width: 320

  test_height: 400
  test_width: 400

  gpus: -1
  batch_size: 20
  accumulate_grad_batches: 1
  max_epochs: 20

  finetune_epochs: 5

  max_steps: 0
  auto_lr_find: 0
  lr: 0.001
  weight_decay: 0.0001

  bitempered_t1: 0.8
  bitempered_t2: 1.2
  label_smoothing: 0.1

  amp_level: 'O2'
  precision: 16

  log_every_n_steps: 10
  flush_logs_every_n_steps: 100



byol:
  width: 400
  height: 400

  gpus: -1
  batch_size: 12
  accumulate_grad_batches: 1
  max_epochs: 100
  max_steps: 0
  auto_lr_find: 0
  lr: 0.001
  reduce_lr_on_pleteau_patience: 1
  weight_decay: 0.0001
  limit_train_batches: 100
  limit_val_batches: 1
  early_stop_patience: 3

  amp_level: '02'
  precision: 16

  log_every_n_steps: 10
  flush_logs_every_n_steps: 100


  on_test:
    lr: 0.0001
    auto_lr_find: 0
    max_epochs: 5
    early_stop_patience: 1

  #limit_train_batches: 2

eval:
  batch_size: 16
